name: full-cycle-ci

on: 
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm test